/*
CLASE 22 SEP 2018

CURSORES

*/

SET SERVEROUTPUT ON;

--1. GENERAR LA SIGUIENTE TABLA
CREATE TABLE empleados(ID INTEGER PRIMARY KEY, 
                       Nombre VARCHAR2(80),
                       Sueldo_Base FLOAT);
--2. GUARDAR LOS SIGUIENTES REGISTROS
INSERT INTO empleados VALUES(1,'Ana',400);
INSERT INTO empleados VALUES(2,'Juan',350);
INSERT INTO empleados VALUES(3,'Pedro',600);
INSERT INTO empleados VALUES(4,'Luis',520);

--MOSTRAR TODA LA TABLA
SELECT * FROM empleados;

--3. CREAR UN CURSOR IMPLICITO (ES UNA SOLA OCURRENCIA)
DECLARE
NUM_EMPLEADOS INTEGER;
BEGIN
--EL SIGUIENTE ES EL CURSOR
SELECT COUNT(*) INTO NUM_EMPLEADOS FROM empleados;
DBMS_OUTPUT.PUT_LINE('LOS EMPLEADOS SON ' || NUM_EMPLEADOS);
END;
/
  