/*
EJERCICIO 1

CREAR UN PROCEDIMIENTO QUE RECIBE UN MENSAJE Y QUE LO IMPRIMA AL INVOCARLO, DARLE EL NOMBRE DE IMPRIMIR
*/

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE IMPRIMIR(MENSA IN VARCHAR2)
AS
BEGIN
DBMS_OUTPUT.PUT_LINE(MENSA);
END;
/

--VAMOS A INVOCARLO INTERNAMENTE,ES DECIR DESDE AQUI EN ORACLE
BEGIN
IMPRIMIR('VAMOS A VER SI FUNCIONA');
END;
/

/*
EJERCICIO 2

CREAR TABLA DACE
*/
--A)CREAR TABLA DANCE
CREATE TABLE DANCE (ID INTEGER PRIMARY KEY, MENSAJE VARCHAR2(80));
/*B) CREAR UN PROCEDIMIENTO ALMACENADOQUE GUARDE UN REGISTROEN ESA TABLA, 
DALE EL NOMBRE DE GUARDAR_DANCE.
EN ESTE CASO COMO NO SE AUTO GENERA EL PRIMARY KEY LOS DOS ARGUMENTOS DEBEN DE SER
DE TIPO DE ENTRADA "IN"*/
CREATE OR REPLACE PROCEDURE GUARDAR_DANCE(VAL1 IN INTEGER,VAL2 IN VARCHAR2)
AS
  BEGIN
  INSERT INTO DANCE VALUES(VAL1,VAL2);
  END;
  /
--PROBAMOS INTERNAMENTE
BEGIN
GUARDAR_DANCE (1,'MI PRIMER MENSAJITO');
END;
/
SELECT * FROM DANCE;
